name: issue
on:
  workflow_run:
    workflows:
      - build
      - lighthouse
      - renovate
    branches:
      - main
    types:
      - completed

jobs:
  create:
    runs-on: ubuntu-latest
    # if: github.event.workflow_run.event == 'push'
    steps:
      - name: Create Issue if the Workflows was Failed
        # if: github.event.workflow_run.conclusion != 'success'
        run: |
          echo "${{ toJson(github) }}"
          echo "Create Issue"
