name: issue
on:
  workflow_run:
    workflows:
      - lint
      - build
    types:
      - completed

jobs:
  create:
    runs-on: ubuntu-latest
    needs:
      - install
      - await-lint
      - test
    steps:
      - name: Create Issue
        run: |
          echo ${{ github.event.workflow_run }}
