name: issue
on:
  workflow_run:
    workflows:
      - build
      - lighthouse
      - renovate
    branches:
      - main
    types:
      - completed

jobs:
  can-create:
    runs-on: ubuntu-latest
    steps:
      - name: Skip Next Job if the Workflows Was Success
        continue-on-error: true
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          echo '::error::the workflows was success'
          echo 1
  create:
    runs-on: ubuntu-latest
    if: failure() && github.event.workflow_run.event == 'push'
    needs:
      - can-create
    steps:
      - name: Create Issue
        run: |
          echo "Create Issue"
          echo 0
