name: issue
on:
  workflow_run:
    workflows:
      - lint
      - build
      - lighthouse
    branches:
      - main
    types:
      - completed

jobs:
  create:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'push'
    steps:
      - name: Create Issue
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo "Create Issue"
