name: issue
on:
  workflow_run:
    workflows:
      - build
      - lighthouse
      - renovate
    branches:
      - main
    types:
      - completed

jobs:
  create:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Create Issue if the Workflows was Failed
        if: github.event.workflow_run.conclusion != 'success'
        run: |
          echo "Create Issue"
