name: issue
on:
  workflow_run:
    workflows:
      - build
      - lighthouse
      - renovate
    branches:
      - main
    types:
      - completed

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue if the Workflows was Failed
        if: github.event.workflow_run.conclusion == 'failure'
        run: |
          echo "Create Issue"
