name: issue
on:
  workflow_run:
    workflows:
      - lint
      - build
      - lighthouse
    branches:
      - main
    types:
      - completed

jobs:
  create:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Create Issue
        run: |
          echo ${{ github.event.workflow_run }}
