name: issue
on:
  workflow_run:
    workflows:
      - build
      - lighthouse
    branches:
      - main
    types:
      - completed

jobs:
  create:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: Create Issue if the Workflows was Failed
        run: |
          echo "Create Issue"
