name: lint
on:
  - pull_request
  - push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Get Yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install npm
        run: |
            yarn --frozen-lockfile
  pre-lint:
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - run: |
          echo 'dummy'
  lint:
    runs-on: ubuntu-latest
    needs:
      - pre-lint
    steps:
      - name: Check Type
        run: |
          npm run ci:check:type
      - name: Check Code Format
        run: |
          npm run ci:check:format
      - name: Lint Code
        run: |
          npm run lint
  lint-mince:
    runs-on: ubuntu-latest
    needs:
      - pre-lint
    steps:
      - name: Lint Markdown
        run: |
          echo 'Lint Markdown'
      - name: Lint Config
        run: |
          echo 'Lint Config'
      - name: Lint Commit
        run: |
          echo 'Lint Commit'
