name: renovate
on:
  # schedule:
  #   - cron: "0 8 * * MON"
  push:
    branches:
      - renovate
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade the Npm library
        run: |
          echo 'Upgrade the Npm library'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v23.100.5
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
        env:
          LOG_LEVEL: debug
